### ISSUE TITLE
F-Droid can't build - Android-SingleSignOn missing

### ISSUE THREAD

**Issue by licaon-kter** [zorgluf/souvenirs-android#18]
For https://github.com/zorgluf/souvenirs-android/releases/tag/v2.8.0
```
...
> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsRelease
> Task :app:dataBindingMergeDependencyArtifactsRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsRelease'.
> Could not resolve all files for configuration ':app:releaseCompileClasspath'.
   > Could not resolve com.github.nextcloud:Android-SingleSignOn:0.6.0.
     Required by:
         project :app
      > Skipped due to earlier error
```
Ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3095002610#L759

And I can repro locally: https://mvnrepository.com/artifact/com.github.nextcloud/Android-SingleSignOn?repo=mulesoft-public

**Comment by zorgluf** [comment]
Thanks for the report, but the com.github.nextcloud:Android-SingleSignOn:0.6.0 dependency is to be found on jitpack.io (https://github.com/nextcloud/Android-SingleSignOn), not on mvnrepository.com.
Since version 2.4.1 (march 2022), I was using this dep without problems with F-droid compiler.
What can I do to make it work again.
(by the way, there is a 0.6.1 newer version on jitpack and I used it on last version 2.8.1, if it helps)
Thanks in advance for your help,

**Comment by licaon-kter** [comment]
:+1: https://gitlab.com/fdroid/fdroiddata/-/commit/a219fcfb31a0873002a070981d624851257e7c0b
