### ISSUE TITLE
Allow adding photos in your nextcloud

### ISSUE THREAD

**Issue by Sorunome** [zorgluf/souvenirs-android#9]
With the nextcloud integration it'd be nice if you could add photos to your photo album which are already in your nextcloud, so that you don't have to re-upload them

**Comment by zorgluf** [comment]
Nice suggestion, I was also thinking about it.
However not so easy to implement, I will give it a try.
Thks for this suggestion.

**Comment by zorgluf** [comment]
Not exactly the feature asked (didn't get a way to cleanly grab the full path of images on android file selector, due to the new provider API and the way nextcloud app handle file informations through his storage provider), but I think I kept the final goal of the issue : do not store twice the file on nextcloud server.
The main job is done on nextcloud souvenirs app : through the commit [3948b7637df7cc8a18f498a38649682cc48219e1](https://github.com/zorgluf/souvenirs-nextcloud/commit/3948b7637df7cc8a18f498a38649682cc48219e1) and [ec3ed39](https://github.com/zorgluf/souvenirs-android/commit/ec3ed39a8dc25340d3aab62196b76c3e7117931c). It enables to create link files on server side in the album directories.
Should be merged and published in june after a couple of more bug fixes.
